/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeMirror5: typeof import('./components/CodeMirror/src/codeMirror5/index.vue')['default']
    ColSetting: typeof import('./components/ProTable/src/components/ColSetting.vue')['default']
    DialogOperate: typeof import('./components/ProTable/src/components/DialogOperate.vue')['default']
    DragDrawerTrigger: typeof import('./components/DragDrawer/src/DragDrawerTrigger.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FontIcon: typeof import('./components/Icon/src/components/vue/FontIcon.vue')['default']
    GridItem: typeof import('./components/Grid/src/components/GridItem.vue')['default']
    IconifyOffline: typeof import('./components/Icon/src/components/vue/IconifyOffline.vue')['default']
    IconifyOnline: typeof import('./components/Icon/src/components/vue/IconifyOnline.vue')['default']
    Image: typeof import('./components/ImagesUpload/src/image.vue')['default']
    Images: typeof import('./components/ImagesUpload/src/images.vue')['default']
    ProFormItem: typeof import('./components/ProForm/src/components/ProFormItem.vue')['default']
    Role: typeof import('./components/Permission/src/role.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFormItem: typeof import('./components/SearchForm/src/components/SearchFormItem.vue')['default']
    SplitLine: typeof import('./components/SplitPane/src/SplitLine.vue')['default']
    Src: typeof import('./components/CodeMirror/src/index.vue')['default']
    SvgIcon: typeof import('./components/Icon/src/components/vue/SvgIcon.vue')['default']
    TableColumn: typeof import('./components/ProTable/src/components/TableColumn.vue')['default']
    Tree: typeof import('./components/ProForm/src/components/Tree.vue')['default']
    VideoPlayerViewer: typeof import('./components/VideoPlayer/src/videoPlayerViewer.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
